### ISSUE TITLE
Take image assets into account for content meta preview and subitems preview

### ISSUE THREAD

**Issue by homarx** [ezsystems/ezplatform-admin-ui-modules#228]
When browsing content in admin interface images are shown in content meta preview for contents which contain an image of the field type ezimage.
This feature could be expanded by displaying an image which is added as image asset (field type ezimageasset) to the content too.

For that content.meta.preview.component.js has to be adjusted, I think.

The same behaviour appears in subitems preview. Image assets fields are not taken into account when displaying thumbs.

**Comment by dew326** [comment]
Hi @homarx, we are working on the content thumbnail so you will be able to set whatever field type you like as a thumbnail and this image will be used for content meta preview, subitems and in all other places where we have to display an image for content. This feature is planned for 3.0.

Here is the Jira ticket: https://jira.ez.no/browse/EZP-30882 and here is one of the required PRs https://github.com/ezsystems/ezpublish-kernel/pull/2868

**Comment by homarx** [comment]
Thank you Dariusz for this information!
