### ISSUE TITLE
UDW in ezobjectrelationlist: Search Component does not take ctofAllowedContentType config

### ISSUE THREAD

**Issue by maczuk** [ezsystems/ezplatform-admin-ui-modules#230]
I'm searching for content in ezobjectrelationlist field type with content type limitation set. UDW does not pass this configuration from `UniversalDiscoveryModule` to `SearchComponent`. Because of that search results have contents that can not be used (wrong content type).

Tech details:
**1) field of ezobjectrelationlist field type with configured content type limitation**
![eZ Platform 2019-11-27 12-03-39](https://user-images.githubusercontent.com/5550410/69718254-2f5c1680-110e-11ea-90ce-e5d89e142ed9.png)

**2)  query only with search text but no content type limitation -> search results with tons of contents of invalid content type**
![eZ Platform 2019-11-27 12-08-10](https://user-images.githubusercontent.com/5550410/69718879-a645df00-110f-11ea-8089-47951a5dcb46.png)

**Comment by maczuk** [comment]
I have created PR for this [PR#231](https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/231)

What do you think?

**Comment by dew326** [comment]
Hi, we are using Jira. Ticket for this issue is already created: https://jira.ez.no/browse/EZP-31194
